---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_server_facts:
         filters:
           name: R1
     - set_fact:
          mikrotik_ipv4: "{{ openstack_servers | json_query('[].public_v4') | join('\n') }}"
          mikrotik_ipv6: "{{ openstack_servers | json_query('[].public_v6') | join('\n') }}"
          mikrotik_id: "{{ openstack_servers | json_query('[].id') | join('\n') }}"
     - os_port_facts:
         filters:
           device_id: "{{ mikrotik_id }}"
     - set_fact:
          query_gw_v4: "[?ip_address=='{{ mikrotik_ipv4 }}'].subnet_id"
          query_gw_v6: "[?ip_address=='{{ mikrotik_ipv6 }}'].subnet_id"
          subnet_id_v4: "{{ openstack_ports | json_query('[].fixed_ips[]') }}"
          subnet_id_v6: "{{ openstack_ports | json_query('[].fixed_ips[]') }}"
     - set_fact:
          subnet_id_v4: "{{ subnet_id_v4 | json_query(query_gw_v4) | join('\n') }}"
          subnet_id_v6: "{{ subnet_id_v6 | json_query(query_gw_v6) | join('\n') }}"
     - os_subnets_facts:
         filters:
           id: "{{ subnet_id_v4 }}"
     - set_fact:
          gw_ipv4: "{{ openstack_subnets | json_query('[].gateway_ip') | join('\n') }}"
          cidr_ipv4: "{{ openstack_subnets | json_query('[].cidr') | join('\n') }}"
     - os_subnets_facts:
         filters:
           id: "{{ subnet_id_v6 }}"
     - set_fact:
          gw_ipv6: "{{ openstack_subnets | json_query('[].gateway_ip') | join('\n') }}"
          cidr_ipv6: "{{ openstack_subnets | json_query('[].cidr') | join('\n') }}"

- hosts: R1
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
  pre_tasks:
     - set_fact:
          gw_ipv4: "{{ hostvars['localhost']['gw_ipv4'] }}"
          mikrotik_ipv4: "{{ hostvars['localhost']['mikrotik_ipv4'] }}"

  roles:
    - hoplacloud.mikrotik
