---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_server_facts:
     - set_fact:
          mikrotik_ipv4: "{{ openstack_servers | json_query('[].public_v4') }}"
          mikrotik_ipv6: "{{ openstack_servers | json_query('[].public_v6') }}"
     - set_fact:
          mikrotik_ipv4: "{{ mikrotik_ipv4 | join('\n') }}"
          mikrotik_ipv6: "{{ mikrotik_ipv6 | join('\n') }}"
- hosts: R1
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
    ansible_ssh_common_args: "-o PreferredAuthentications=password -o PubkeyAuthentication=no"
  tasks:
     - name: Display resource statistics (routeros)
       routeros_command:
         commands: /system resource print
