---
- hosts: R1
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
    ansible_password:
  tasks:
    - name: Display resource statistics (routeros)
      routeros_command:
        commands: /system resource print
