---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_server_facts:
     - debug:
         var: openstack_servers.addresses[]|.[1].addr
     - name: "Display all cluster names"
       debug:
         var: item
       loop: "{{ openstack_servers | json_query('.addresses[]|.[1].addr') }}"
