galaxy_info:
  role_name: openstack-instance-exemple
  author: Joffrey Skandera
  description: Hopla.cloud exemple role for ansible.
  company: hopla.cloud

  license: GPLv3

  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - openstack
