---
# tasks file for hoplacloud.mikrotik
 - name:
   routeros_command:
     commands: /ip route add distance=1 gateway="{{ gw_ipv4 }}"

 - name:
   routeros_command:
     commands: /ip address add address="{{ mikrotik_ipv4 }}"/24 interface=ether1

 - name: Disable dhcp package
   routeros_command:
     commands: /system package disable dhcp

 - name: Disable wireless package
   routeros_command:
     commands: /system package disable wireless

 - name: Disable hotspot package
   routeros_command:
     commands: /system package disable hotspot

 - name: Disable mpls package
   routeros_command:
     commands: /system package disable mpls

 - name: Disable ups package
   routeros_command:
     commands: /system package disable ups

 - name: Enable IPv6
   routeros_command:
     commands: /system package enable ipv6

 - name: Disable services
   routeros_command:
     commands: /ip service disable telnet,ftp,www,api,api-ssl,www-ssl

 - name:
   routeros_command:
     commands: /ip address add address=10.15.30.254/24 interface=ether2

 - name:
   routeros_command:
     commands: /ip address add address=10.15.31.254/24 interface=ether3
   when: (lan2|bool == true)

 - name:
   routeros_command:
     commands: /system logging add action=disk topics=critical

 - name:
   routeros_command:
     commands: /system logging add action=disk topics=error

 - name:
   routeros_command:
     commands: /system logging add action=disk topics=info

 - name:
   routeros_command:
     commands: /system logging add action=disk topics=warning

 - name:
   routeros_command:
     commands: /system logging action set 1 disk-file-count=20
